import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'


export default function Home() {
  const [data, setData] = useState([])
  useEffect(() => {
    fetch('https://api.sampleapis.com/wines/reds')
      .then(res => res.json())
      .then(wines => setData(wines))
      .catch(err => console.error(err))

  }, []);
  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Adi next js app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>

          {data.map(x => <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>{x.wine} &rarr;</h2>
            <p>{x.location}</p>
          </a>)}

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
